# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  range: 85..100
  round: down
  precision: 0.1
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        threshold: 1%

ignore:
  - "tests"

# Make comments less noisy
comment:
  layout: "files"
  require_changes: true
