name: Deploy Docs

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Generate documentation
      run: |
        cargo doc --no-deps --document-private-items
        echo '<!DOCTYPE html>
        <html>
        <head>
            <meta http-equiv="refresh" content="0; url=data_forest/index.html">
            <title>Redirecting...</title>
            <script>window.location.href="data_forest/index.html"</script>
        </head>
        <body>
            <p>If you are not redirected, <a href="data_forest/index.html">click here</a>.</p>
        </body>
        </html>' > target/doc/index.html
        
        touch target/doc/.nojekyll
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        keep_files: false  
